#!/bin/bash
# Usage: ./run_CVRP_Belgium class name max_trials runs [ optimum ]

if [ -z "$2" ]; then
    echo "./run_CVRP_Belgium name max_trials runs [ optimum ]"
    exit
fi

lkh="../LKH"
class="Belgium"
name=$1
max_trials=$2
runs=$3
seed=$4
optimum=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/$class
mkdir -p TMP

echo "SPECIAL" >$par
echo "PROBLEM_FILE = INSTANCES/$class/$name.vrp" >>$par
echo "INITIAL_PERIOD = 1000" >>$par
echo "MAX_TRIALS = $max_trials" >>$par
echo "RUNS = $runs" >>$par
echo "TRACE_LEVEL = 1" >>$par
echo "SEED = ${seed}" >>$par

$lkh $par

/bin/rm -f $par
