#!/bin/bash
# Usage: ./run_VRPB class name max_trials runs [ optimum ]

if [ -z "$4" ]; then
    echo "./run_VRPB class name max_trials runs [ optimum ]"
    exit
fi

lkh="../LKH"
class=$1
name=$2
max_trials=$3
runs=$4
optimum=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/$class
mkdir -p TMP

echo "SPECIAL" > $par
echo "PROBLEM_FILE = INSTANCES/$class/$name.vrpb" >> $par
echo "MAX_TRIALS = $max_trials" >> $par
echo "POPULATION_SIZE = 10" >> $par
echo "PRECISION = 1" >> $par
echo "RUNS = $runs" >> $par
# echo "SCALE = 100" >> $par
# echo "TOUR_FILE = TOURS/$class/$name.$.tour" >> $par
echo "TRACE_LEVEL = 0" >> $par

if false; then
    for FILE in `ls TOURS/$class/$name.*.tour | sort -n -t . -k2,3` ;
    do
        echo "INITIAL_TOUR_FILE = $FILE" >> $par
        break
    done
fi

if [ -n "$optimum" ]; then
    echo "OPTIMUM = $optimum" >> $par
fi

$lkh $par

/bin/rm -f $par
